from __future__ import annotations

import json
import logging
import re
from pathlib import Path

import anthropic

from config import settings
from models.form_schema import AnalysisResult
from models.traffic import TrafficEntry
from security import mask_sensitive_headers
from ws.stream import ConnectionManager

logger = logging.getLogger(__name__)

CODEGEN_SYSTEM_PROMPT = """\
You are an expert Python developer specializing in FastAPI. Your task is to generate
a complete, working FastAPI server that replicates the API endpoints discovered from
analyzing a website's traffic.

You will receive:
1. An analysis of the API (endpoints, auth method, data patterns)
2. User-provided credentials and configuration
3. Original traffic samples for reference

Generate a complete FastAPI project. Output each file using this EXACT format:

=== FILE: main.py ===
(file content here)
=== FILE: requirements.txt ===
(file content here)
=== FILE: README.md ===
(file content here)
=== END ===

Requirements:
- Use httpx for making requests to the original API
- Implement proper authentication handling based on the detected auth method
- NEVER hardcode credentials, cookies, tokens, or API keys as literals in the
  code. Read every secret from environment variables (os.environ / os.getenv)
  or a .env file loaded at startup. Also emit a `.env.example` file listing
  every required variable with empty/placeholder values.
- Include request/response models using Pydantic
- Add proper error handling
- Include CORS middleware
- Add docstrings in Korean
- The server should act as a working proxy/client that can be used to interact with the original API
- The FIRST lines of README.md MUST be a clearly-marked security warning, in
  Korean, stating that this code was generated by AI from captured traffic of a
  third-party site, that it must be reviewed before running, that secrets are
  read from environment variables (never committed), and that the user must be
  authorized to access the target API.

Output ONLY the files in the format above. No extra explanation.\
"""

FILE_MARKER_RE = re.compile(r"^=== FILE: (.+?) ===$", re.MULTILINE)


class CodeGenerator:
    def __init__(self) -> None:
        self._client: anthropic.AsyncAnthropic | None = None
        self._ws: ConnectionManager | None = None
        self._init_client()

    def _init_client(self) -> None:
        if settings.is_api_key_set:
            self._client = anthropic.AsyncAnthropic(
                api_key=settings.anthropic_api_key,
            )
        else:
            self._client = None

    def set_ws(self, ws_manager: ConnectionManager) -> None:
        self._ws = ws_manager

    def reload(self) -> None:
        self._init_client()
        logger.info("CodeGenerator reloaded (key set: %s, model: %s)",
                     settings.is_api_key_set, settings.claude_model)

    async def generate(
        self,
        analysis: AnalysisResult,
        user_inputs: dict[str, str],
        entries: list[TrafficEntry],
        project_name: str = "generated_api",
        output_dir: Path | None = None,
    ) -> dict[str, str]:
        """Generate a FastAPI server with real-time streaming."""

        analysis_json = analysis.model_dump_json(indent=2)

        sample_entries = entries[:10]
        samples = []
        for entry in sample_entries:
            samples.append({
                "method": entry.request_method,
                "url": entry.request_url,
                "request_headers": mask_sensitive_headers(entry.request_headers),
                "request_body": (entry.request_body or "")[:500],
                "response_status": entry.response_status,
                "response_body": (entry.response_body or "")[:500],
            })

        logger.info("Generating API server code (streaming) for: %s", project_name)

        if self._client is None:
            raise RuntimeError("Anthropic API key is not configured. Go to Settings.")

        # Stream the response
        full_text = ""
        current_file = ""
        content_start = 0   # Position in full_text where current file content begins
        last_sent = 0       # How much of full_text we've sent as chunks

        async with self._client.messages.stream(
            model=settings.claude_model,
            max_tokens=16384,
            system=CODEGEN_SYSTEM_PROMPT,
            messages=[
                {
                    "role": "user",
                    "content": (
                        f"## API 분석 결과\n{analysis_json}\n\n"
                        f"## 사용자 입력 정보\n{json.dumps(user_inputs, ensure_ascii=False, indent=2)}\n\n"
                        f"## 트래픽 샘플 (참고용)\n{json.dumps(samples, ensure_ascii=False, indent=2)}\n\n"
                        "위 정보를 기반으로 완전한 FastAPI 서버를 생성해주세요. "
                        "원본 API와 동일한 기능을 제공하되, 사용자가 제공한 인증 정보를 사용하세요."
                    ),
                }
            ],
        ) as stream:
            async for text in stream.text_stream:
                full_text += text

                # Detect file markers in accumulated text
                new_file = self._detect_current_file(full_text)
                if new_file and new_file != current_file:
                    current_file = new_file
                    # Find where content starts (after the marker line)
                    marker = f"=== FILE: {current_file} ==="
                    marker_pos = full_text.rfind(marker)
                    content_start = marker_pos + len(marker)
                    if content_start < len(full_text) and full_text[content_start] == "\n":
                        content_start += 1
                    last_sent = content_start
                    await self._broadcast("file_start", {
                        "filename": current_file,
                    })

                # Stream clean content (no markers) to frontend
                if current_file and last_sent < len(full_text):
                    chunk = full_text[last_sent:]
                    if chunk:
                        await self._broadcast("chunk", {
                            "filename": current_file,
                            "text": chunk,
                        })
                        last_sent = len(full_text)

        # Parse the complete output into files
        files = self._parse_files(full_text)

        # Save to output directory (prefer explicit output_dir, fallback to settings)
        base = output_dir if output_dir else settings.output_dir
        output_path = base / project_name
        output_path.mkdir(parents=True, exist_ok=True)

        resolved_base = output_path.resolve()
        for filename, content in files.items():
            # The filename comes from the model's output markers — guard against
            # absolute paths and `..` traversal escaping the output directory.
            candidate = (output_path / filename).resolve()
            if candidate != resolved_base and not candidate.is_relative_to(resolved_base):
                logger.warning("Skipping unsafe generated filename: %r", filename)
                continue
            candidate.parent.mkdir(parents=True, exist_ok=True)
            candidate.write_text(content, encoding="utf-8")
            logger.info("Generated: %s", candidate)

        await self._broadcast("complete", {
            "files": list(files.keys()),
        })

        return files

    def _detect_current_file(self, text: str) -> str:
        """Find the last === FILE: xxx === marker in text."""
        matches = FILE_MARKER_RE.findall(text)
        return matches[-1] if matches else ""

    def _parse_files(self, text: str) -> dict[str, str]:
        """Parse the streamed output into individual files."""
        files: dict[str, str] = {}
        parts = FILE_MARKER_RE.split(text)

        # parts: [preamble, filename1, content1, filename2, content2, ...]
        i = 1
        while i < len(parts) - 1:
            filename = parts[i].strip()
            content = parts[i + 1]
            # Remove trailing === END === if present
            content = re.sub(r"\s*=== END ===\s*$", "", content)
            files[filename] = content.strip() + "\n"
            i += 2

        return files

    async def _broadcast(self, event_type: str, data: dict) -> None:
        if self._ws:
            await self._ws.broadcast("codegen", {
                "type": event_type,
                "data": data,
            })


# Module-level singleton
code_generator = CodeGenerator()
