from __future__ import annotations

import json
import logging
import re
from pathlib import Path

import anthropic

from config import settings
from models.form_schema import AnalysisResult
from models.traffic import TrafficEntry
from security import mask_sensitive_headers
from ws.stream import ConnectionManager

logger = logging.getLogger(__name__)

CODEGEN_SYSTEM_PROMPT = """\
You are an expert Python developer specializing in FastAPI. Your task is to generate
a complete, working FastAPI server that replicates the API endpoints discovered from
analyzing a website's traffic.

You will receive:
1. An analysis of the API (endpoints, auth method, data patterns)
2. User-provided credentials and configuration
3. Original traffic samples for reference

Generate a complete FastAPI project. Output each file using this EXACT format:

=== FILE: main.py ===
(file content here)
=== FILE: requirements.txt ===
(file content here)
=== FILE: README.md ===
(file content here)
=== END ===

Requirements:
- Use httpx for making requests to the original API
- Implement proper authentication handling based on the detected auth method
- NEVER hardcode credentials, cookies, tokens, or API keys as literals in the
  code. Read every secret from environment variables (os.environ / os.getenv)
  or a .env file loaded at startup. Also emit a `.env.example` file listing
  every required variable with empty/placeholder values.
- Include request/response models using Pydantic
- Add proper error handling
- Include CORS middleware
- Add docstrings in Korean
- The server should act as a working proxy/client that can be used to interact with the original API
- The FIRST lines of README.md MUST be a clearly-marked security warning, in
  Korean, stating that this code was generated by AI from captured traffic of a
  third-party site, that it must be reviewed before running, that secrets are
  read from environment variables (never committed), and that the user must be
  authorized to access the target API.

Output ONLY the files in the format above. No extra explanation.\
"""

AGENT_SDK_SYSTEM_PROMPT = """\
You are an expert Python developer. Your task is to generate a complete, working
Claude Agent SDK (Python) agent that wraps each discovered API endpoint as an
agent tool, so a user can interact with the reverse-engineered API through Claude
in natural language.

You will receive:
1. An analysis of the API (endpoints, auth method, data patterns)
2. User-provided credentials and configuration
3. Original traffic samples for reference

Generate a complete project. Output each file using this EXACT format:

=== FILE: agent.py ===
(file content here)
=== FILE: tools.py ===
(file content here)
=== FILE: requirements.txt ===
(file content here)
=== FILE: .env.example ===
(file content here)
=== FILE: README.md ===
(file content here)
=== END ===

Use the Claude Agent SDK EXACTLY as specified below. These APIs are verified —
do not deviate, do not invent parameters, do not mix in the Messages API:

- Target Python 3.10+. requirements.txt MUST list exactly these three packages,
  one per line: claude-agent-sdk, httpx, python-dotenv
- Imports (in the files that need them):
  from claude_agent_sdk import tool, create_sdk_mcp_server, ClaudeSDKClient, ClaudeAgentOptions, AssistantMessage, TextBlock
- tools.py: define ONE tool per discovered endpoint:
    @tool(name="<snake_case_name>", description="<what it does>", input_schema={"param": str, ...})
    async def <name>(args: dict) -> dict:
        ...
  * input_schema maps each parameter name to a Python TYPE (str / int / float / bool),
    derived from the endpoint's request_body_schema and any query/path params.
  * Each tool calls the ORIGINAL API using httpx.AsyncClient (await the request),
    injecting credentials read from os.getenv(...) when auth_required is true.
  * Each tool MUST return, on success:
        {"content": [{"type": "text", "text": <string result>}]}
    and on failure:
        {"content": [{"type": "text", "text": <error message>}], "is_error": True}
  * Export a module-level list ALL_TOOLS containing every tool function.
- agent.py:
  * from dotenv import load_dotenv; load_dotenv() at startup.
  * server = create_sdk_mcp_server(name="api", version="1.0.0", tools=ALL_TOOLS)
  * options = ClaudeAgentOptions(
        mcp_servers={"api": server},
        allowed_tools=["mcp__api__<tool_name>", ...],   # one per tool; the part after
                                                         # mcp__api__ MUST equal the @tool name exactly
        system_prompt="<describe the wrapped API and when to use each tool>",
        model="opus",
        permission_mode="acceptEdits",
    )
  * Run an interactive multi-turn CLI loop with ClaudeSDKClient:
        async with ClaudeSDKClient(options=options) as client:
            while True:
                user_input = input("You: ")
                if not user_input or user_input.strip().lower() in {"exit", "quit"}:
                    break
                await client.query(user_input)
                async for message in client.receive_response():
                    if isinstance(message, AssistantMessage):
                        for block in message.content:
                            if isinstance(block, TextBlock):
                                print(block.text)
  * End with: if __name__ == "__main__": asyncio.run(main())

Rules:
- NEVER hardcode credentials, cookies, tokens, or API keys as literals. Read every
  secret from environment variables (os.getenv). Emit a .env.example listing every
  required variable with empty placeholder values — including ANTHROPIC_API_KEY
  (required by the Agent SDK), API_BASE_URL, and one variable per detected credential.
- Use the model alias "opus" (never a dated version string).
- The FIRST lines of README.md MUST be a clearly-marked security warning, in Korean,
  stating that this code was generated by AI from captured traffic of a third-party
  site, that it must be reviewed before running, that secrets are read from environment
  variables (never committed), that the Claude Agent SDK requires ANTHROPIC_API_KEY
  (or a logged-in Claude Code CLI), and that the user must be authorized to access the
  target API. Then include: install (pip install -r requirements.txt), env setup (copy
  .env.example to .env and fill it in), how to run (python agent.py), and the list of
  wrapped endpoint tools.

Output ONLY the files in the format above. No extra explanation.\
"""

FILE_MARKER_RE = re.compile(r"^=== FILE: (.+?) ===$", re.MULTILINE)


class CodeGenerator:
    def __init__(self) -> None:
        self._client: anthropic.AsyncAnthropic | None = None
        self._ws: ConnectionManager | None = None
        self._init_client()

    def _init_client(self) -> None:
        if settings.is_api_key_set:
            self._client = anthropic.AsyncAnthropic(
                api_key=settings.anthropic_api_key,
            )
        else:
            self._client = None

    def set_ws(self, ws_manager: ConnectionManager) -> None:
        self._ws = ws_manager

    def reload(self) -> None:
        self._init_client()
        logger.info("CodeGenerator reloaded (key set: %s, model: %s)",
                     settings.is_api_key_set, settings.claude_model)

    async def generate(
        self,
        analysis: AnalysisResult,
        user_inputs: dict[str, str],
        entries: list[TrafficEntry],
        project_name: str = "generated_api",
        output_dir: Path | None = None,
        target: str = "fastapi",
    ) -> dict[str, str]:
        """Generate an API client/agent project with real-time streaming.

        target: "fastapi" (FastAPI client) or "agent_sdk" (Claude Agent SDK agent).
        """

        analysis_json = analysis.model_dump_json(indent=2)

        sample_entries = entries[:10]
        samples = []
        for entry in sample_entries:
            samples.append({
                "method": entry.request_method,
                "url": entry.request_url,
                "request_headers": mask_sensitive_headers(entry.request_headers),
                "request_body": (entry.request_body or "")[:500],
                "response_status": entry.response_status,
                "response_body": (entry.response_body or "")[:500],
            })

        logger.info("Generating code (streaming, target=%s) for: %s", target, project_name)

        if self._client is None:
            raise RuntimeError("Anthropic API key is not configured. Go to Settings.")

        # Select target-specific system prompt + task instruction
        if target == "agent_sdk":
            system_prompt = AGENT_SDK_SYSTEM_PROMPT
            task_instruction = (
                "위 정보를 기반으로 각 엔드포인트를 agent tool로 래핑하는 "
                "Claude Agent SDK(Python) 에이전트를 생성해주세요. "
                "모든 인증 정보는 환경변수에서 읽으세요."
            )
        else:
            system_prompt = CODEGEN_SYSTEM_PROMPT
            task_instruction = (
                "위 정보를 기반으로 완전한 FastAPI 서버를 생성해주세요. "
                "원본 API와 동일한 기능을 제공하되, 사용자가 제공한 인증 정보를 사용하세요."
            )

        # Stream the response
        full_text = ""
        current_file = ""
        content_start = 0   # Position in full_text where current file content begins
        last_sent = 0       # How much of full_text we've sent as chunks

        async with self._client.messages.stream(
            model=settings.claude_model,
            max_tokens=32768,
            system=system_prompt,
            messages=[
                {
                    "role": "user",
                    "content": (
                        f"## API 분석 결과\n{analysis_json}\n\n"
                        f"## 사용자 입력 정보\n{json.dumps(user_inputs, ensure_ascii=False, indent=2)}\n\n"
                        f"## 트래픽 샘플 (참고용)\n{json.dumps(samples, ensure_ascii=False, indent=2)}\n\n"
                        f"{task_instruction}"
                    ),
                }
            ],
        ) as stream:
            async for text in stream.text_stream:
                full_text += text

                # Detect file markers in accumulated text
                new_file = self._detect_current_file(full_text)
                if new_file and new_file != current_file:
                    current_file = new_file
                    # Find where content starts (after the marker line)
                    marker = f"=== FILE: {current_file} ==="
                    marker_pos = full_text.rfind(marker)
                    content_start = marker_pos + len(marker)
                    if content_start < len(full_text) and full_text[content_start] == "\n":
                        content_start += 1
                    last_sent = content_start
                    await self._broadcast("file_start", {
                        "filename": current_file,
                    })

                # Stream clean content (no markers) to frontend
                if current_file and last_sent < len(full_text):
                    chunk = full_text[last_sent:]
                    if chunk:
                        await self._broadcast("chunk", {
                            "filename": current_file,
                            "text": chunk,
                        })
                        last_sent = len(full_text)

        # Parse the complete output into files
        files = self._parse_files(full_text)

        # Save to output directory (prefer explicit output_dir, fallback to settings)
        base = output_dir if output_dir else settings.output_dir
        output_path = base / project_name
        output_path.mkdir(parents=True, exist_ok=True)

        resolved_base = output_path.resolve()
        for filename, content in files.items():
            # The filename comes from the model's output markers — guard against
            # absolute paths and `..` traversal escaping the output directory.
            candidate = (output_path / filename).resolve()
            if candidate != resolved_base and not candidate.is_relative_to(resolved_base):
                logger.warning("Skipping unsafe generated filename: %r", filename)
                continue
            candidate.parent.mkdir(parents=True, exist_ok=True)
            candidate.write_text(content, encoding="utf-8")
            logger.info("Generated: %s", candidate)

        await self._broadcast("complete", {
            "files": list(files.keys()),
        })

        return files

    def _detect_current_file(self, text: str) -> str:
        """Find the last === FILE: xxx === marker in text."""
        matches = FILE_MARKER_RE.findall(text)
        return matches[-1] if matches else ""

    def _parse_files(self, text: str) -> dict[str, str]:
        """Parse the streamed output into individual files."""
        files: dict[str, str] = {}
        parts = FILE_MARKER_RE.split(text)

        # parts: [preamble, filename1, content1, filename2, content2, ...]
        i = 1
        while i < len(parts) - 1:
            filename = parts[i].strip()
            content = parts[i + 1]
            # Remove trailing === END === if present
            content = re.sub(r"\s*=== END ===\s*$", "", content)
            files[filename] = content.strip() + "\n"
            i += 2

        return files

    async def _broadcast(self, event_type: str, data: dict) -> None:
        if self._ws:
            await self._ws.broadcast("codegen", {
                "type": event_type,
                "data": data,
            })


# Module-level singleton
code_generator = CodeGenerator()
